import BaseSeeder from "@ioc:Adonis/Lucid/Seeder";
import Budgets from "App/Models/Budgets";
import { DateTime } from "luxon";

export default class extends BaseSeeder {
  public async run() {
    //Write your database queries inside the run method
    await Budgets.createMany([
      {
        id: 1,
        number: "92180401",
        denomination: "Cuota de fiscalización y auditaje",
        description: "Cuota de fiscalización y auditaje",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 2,
        number: "92110102001",
        denomination: "Aportes a la seguridad social en pensiones",
        description: "Aportes a la seguridad social en pensiones",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 3,
        number: "92110102002",
        denomination: "Aportes a la seguridad social en salud",
        description: "Aportes a la seguridad social en salud",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 4,
        number: "92110102003",
        denomination: "Aportes de cesantías	",
        description: "Aportes de cesantías	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 5,
        number: "92110102004",
        denomination: "Aportes a cajas de compensación familiar	",
        description: "Aportes a cajas de compensación familiar	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 6,
        number: "92110102005",
        denomination: "Aportes generales al sistema de riesgos laborales	",
        description: "Aportes generales al sistema de riesgos laborales	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 7,
        number: "92110102006",
        denomination: "Aportes al ICBF	",
        description: "Aportes al ICBF	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 8,
        number: "92110102007",
        denomination: "Aportes al SENA	",
        description: "Aportes al SENA	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 9,
        number: "92120201003",
        denomination: "Otros bienes transportab (exc prod met, maq y equ)	",
        description: "Otros bienes transportab (exc prod met, maq y equ)	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 10,
        number: "92120202006",
        denomination: "Serv alojam; comida; transp; y electr, gas y agua	",
        description: "Serv alojam; comida; transp; y electr, gas y agua	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 11,
        number: "92120202007",
        denomination: "Ser financ y conexos, serv inmobiliarios y leasing	",
        description: "Ser financ y conexos, serv inmobiliarios y leasing	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 12,
        number: "92120202008",
        denomination: "Servicios prestados a empr y servicios producción	",
        description: "Servicios prestados a empr y servicios producción	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 13,
        number: "92120202009",
        denomination: "Servicios para la comunidad, sociales y personales	",
        description: "Servicios para la comunidad, sociales y personales	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 14,
        number: "9211010100105",
        denomination: "Auxilio de transporte	",
        description: "Auxilio de transporte	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 15,
        number: "9211010100106",
        denomination: "Prima de servicios	",
        description: "Prima de servicios	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 16,
        number: "9211010100107",
        denomination: "Bonificación por servicios prestados	",
        description: "Bonificación por servicios prestados	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 17,
        number: "9211010300101",
        denomination: "Vacaciones",
        description: "Vacaciones",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 18,
        number: "9211010300103",
        denomination: "Bonificación por recreación	",
        description: "Bonificación por recreación	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 19,
        number: "9212020100200",
        denomination: "Otr prod alim, beb, textiles, pr vestir y prod cue	",
        description: "Otr prod alim, beb, textiles, pr vestir y prod cue	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 20,
        number: "9212020100300",
        denomination: "Otros bienes transportables difere (exc maq y equ)	",
        description: "Otros bienes transportables difere (exc maq y equ)	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 21,
        number: "9212020100400",
        denomination: "Otros productos metálicos y paquetes de software	",
        description: "Otros productos metálicos y paquetes de software	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 22,
        number: "9212020200609",
        denomination: "Serv de distribución de electricidad, gas y agua	",
        description: "Serv de distribución de electricidad, gas y agua	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 23,
        number: "9212020200800",
        denomination: "Otros servicios prestados a empr y serv producción	",
        description: "Otros servicios prestados a empr y serv producción	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 24,
        number: "9212020200804",
        denomination: "Serv de telecomunicaciones, transm y sumin de inf	",
        description: "Serv de telecomunicaciones, transm y sumin de inf	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 25,
        number: "9212020200902",
        denomination: "Servicios de educación	",
        description: "Servicios de educación	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 26,
        number: "9212020200904",
        denomination: "Serv alcantarillado, recol, desechos y otros serv	",
        description: "Serv alcantarillado, recol, desechos y otros serv	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 27,
        number: "921101010010101",
        denomination: "Sueldo básico Empleados	",
        description: "Sueldo básico Empleados	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 28,
        number: "921101010010801",
        denomination: "Prima de navidad	",
        description: "Prima de navidad	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 29,
        number: "921101010010802",
        denomination: "Prima de vacaciones	",
        description: "Prima de vacaciones	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 30,
        number: "921202020080502",
        denomination: "Servicios de investigación y seguridad	",
        description: "Servicios de investigación y seguridad	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 31,
        number: "92320201002",
        denomination: "Prod alime, beb, textiles, pr vestir y prod cuero	",
        description: "Prod alime, beb, textiles, pr vestir y prod cuero	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 32,
        number: "92320201003",
        denomination: "Otros bienes transportab (exc prod met, maq y equ)	",
        description: "Otros bienes transportab (exc prod met, maq y equ)	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 33,
        number: "92320201004",
        denomination: "Productos metálicos y paquetes de software	",
        description: "Productos metálicos y paquetes de software	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 34,
        number: "92320202006",
        denomination: "Serv alojam; comida; transp; y electr, gas y agua	",
        description: "Serv alojam; comida; transp; y electr, gas y agua	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 35,
        number: "92320202007",
        denomination: "Servicios financieros y servicios conexos	",
        description: "Servicios financieros y servicios conexos	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 36,
        number: "92320202008",
        denomination: "Servicios prestados a empr y servicios producción	",
        description: "Servicios prestados a empr y servicios producción	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 37,
        number: "92320202009",
        denomination: "Servicios para la comunidad, sociales y personales	",
        description: "Servicios para la comunidad, sociales y personales	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      },
      {
        id: 38,
        number: "923201010030302",
        denomination: "Maqu informática y sus partes, piezas y accesorios	",
        description: "Maqu informática y sus partes, piezas y accesorios	",
        ejercise: 2023,
        entityId: 1,
        dateCreate: DateTime.now(),
      }
    ]);
  }
}
