import BaseSeeder from "@ioc:Adonis/Lucid/Seeder";
import ProductClassification from "App/Models/ProductClassification";
import { DateTime } from "luxon";

export default class extends BaseSeeder {
  public async run() {
    //Write your database queries inside the run method
    await ProductClassification.createMany([
      {
        id: 1,
        budgetId: 9,
        number: "3899998",
        description: "Artículos n.c.p. para escritorio y oficina",
        dateCreate: DateTime.now(),
      },
      {
        id: 2,
        budgetId: 10,
        number: "64114",
        description: "Servicios de transporte terrestre especial local de pasajeros",
        dateCreate: DateTime.now(),
      },
      {
        id: 3,
        budgetId: 10,
        number: "67913",
        description: "Servicios de operación de transporte terrestre (pasajeros y mercancía)",
        dateCreate: DateTime.now(),
      },
      {
        id: 4,
        budgetId: 10,
        number: "68021",
        description: "Servicios locales de mensajería nacional",
        dateCreate: DateTime.now(),
      },
      {
        id: 5,
        budgetId: 11,
        number: "71359",
        description: "Otros servicios de seguros distintos de los seguros de vida n.c.p.",
        dateCreate: DateTime.now(),
      },
      {
        id: 6,
        budgetId: 12,
        number: "84342",
        description: "Servicios de descarga de software de aplicaciones",
        dateCreate: DateTime.now(),
      },
      {
        id: 7,
        budgetId: 12,
        number: "85330",
        description: "Servicios de limpieza general",
        dateCreate: DateTime.now(),
      },
      {
        id: 8,
        budgetId: 13,
        number: "91121",
        description: "Servicios de la administración pública relacionados con la educación",
        dateCreate: DateTime.now(),
      },
      {
        id: 9,
        budgetId: 13,
        number: "91122",
        description: "Servicios de la administración pública relacionados con la salud",
        dateCreate: DateTime.now(),
      },
      {
        id: 10,
        budgetId: 19,
        number: "2823609",
        description: "Uniformes de trabajo",
        dateCreate: DateTime.now(),
      },
      {
        id: 11,
        budgetId: 20,
        number: "3711604",
        description: "Espejos sin marco 450.000",
        dateCreate: DateTime.now(),
      },
      {
        id: 12,
        budgetId: 20,
        number: "3335099",
        description: "Disolventes n.c.p. derivados del petróleo 15.000",
        dateCreate: DateTime.now(),
      },
      {
        id: 13,
        budgetId: 21,
        number: "4299991",
        description: "Artículos n.c.p. de ferretería y cerrajería",
        dateCreate: DateTime.now(),
      },
      {
        id: 14,
        budgetId: 22,
        number: "69112",
        description: "Servicios de distribución de electricidad (por cuenta propia)",
        dateCreate: DateTime.now(),
      },
      {
        id: 15,
        budgetId: 23,
        number: "85999",
        description: "Otros servicios de apoyo n.c.p.",
        dateCreate: DateTime.now(),
      },
      {
        id: 16,
        budgetId: 24,
        number: "84131",
        description: "Servicios móviles de voz",
        dateCreate: DateTime.now(),
      },
      {
        id: 17,
        budgetId: 24,
        number: "3899998",
        description: "Servicios de acceso a Internet de banda ancha",
        dateCreate: DateTime.now(),
      },
      {
        id: 18,
        budgetId: 25,
        number: "91121",
        description: "Servicios de la administración pública relacionados con la educación",
        dateCreate: DateTime.now(),
      },
      {
        id: 19,
        budgetId: 26,
        number: "94110",
        description: "Servicios de alcantarillado y tratamiento de aguas residuales",
        dateCreate: DateTime.now(),
      },
      {
        id: 20,
        budgetId: 30,
        number: "83990",
        description: "Otros servicios profesionales, técnicos y empresariales n.c.p.",
        dateCreate: DateTime.now(),
      },
      {
        id: 21,
        budgetId: 31,
        number: "2719007",
        description: "Filtros de material textil, para usos técnicos e industriales",
        dateCreate: DateTime.now(),
      },
      {
        id: 22,
        budgetId: 32,
        number: "Partes y accesorios de material plástico para elementos de protección",
        description: "",
        dateCreate: DateTime.now(),
      },
      {
        id: 23,
        budgetId: 33,
        number: "45269",
        description: "Otros dispositivos periféricos de entrada o salida",
        dateCreate: DateTime.now(),
      },
      {
        id: 24,
        budgetId: 33,
        number: "47814",
        description: "Paquetes de software de herramientas de desarrollo y lenguajes de programación",
        dateCreate: DateTime.now(),
      },
      {
        id: 25,
        budgetId: 33,
        number: "4621199",
        description: "Aparatos para carga, conversión y control y regulación de corriente n.c.p.",
        dateCreate: DateTime.now(),
      },
      {
        id: 26,
        budgetId: 33,
        number: "4732301",
        description: "Aparatos de grabación o de reproducción de imagen y sonido (videos) de cinta magnética",
        dateCreate: DateTime.now(),
      },
      {
        id: 27,
        budgetId: 34,
        number: "61200",
        description: "Comercio al por mayor prestados a comisión o por contrata",
        dateCreate: DateTime.now(),
      },
      {
        id: 28,
        budgetId: 34,
        number: "62165",
        description: "Comercio al por menor de artículos de ferretería y herramientas manuales, en establecimientos no especializados",
        dateCreate: DateTime.now(),
      },
      {
        id: 29,
        budgetId: 34,
        number: "64114",
        description: "Servicios de transporte terrestre especial local de pasajeros",
        dateCreate: DateTime.now(),
      },
      {
        id: 30,
        budgetId: 34,
        number: "68021",
        description: "Servicios locales de mensajería nacional",
        dateCreate: DateTime.now(),
      },
      {
        id: 31,
        budgetId: 34,
        number: "69112",
        description: "Servicios de distribución de electricidad (por cuenta propia)",
        dateCreate: DateTime.now(),
      },
      {
        id: 32,
        budgetId: 35,
        number: "71359",
        description: "Otros servicios de seguros distintos de los seguros de vida n.c.p",
        dateCreate: DateTime.now(),
      },
      {
        id: 33,
        budgetId: 35,
        number: "72112",
        description: "Servicios de administración de bienes inmuebles no residenciales (diferentes a vivienda) a comisión o por contrato",
        dateCreate: DateTime.now(),
      },
      {
        id: 34,
        budgetId: 35,
        number: "73129",
        description: "Servicios de arrendamiento sin opción de compra de maquinaria y equipo sin operario n.c.p.",
        dateCreate: DateTime.now(),
      },
      {
        id: 35,
        budgetId: 35,
        number: "73312",
        description: "Derechos de uso de bases de datos",
        dateCreate: DateTime.now(),
      },
      {
        id: 36,
        budgetId: 36,
        number: "83132",
        description: "Servicios de soporte en tecnologías de la información (TI)",
        dateCreate: DateTime.now(),
      },
      {
        id: 37,
        budgetId: 36,
        number: "83159",
        description: "Otros servicios de alojamiento y suministro de infraestructura en tecnología de la información (TI)",
        dateCreate: DateTime.now(),
      },
      {
        id: 38,
        budgetId: 36,
        number: "83700",
        description: "Servicios de investigación de mercados y encuestas de opinión pública",
        dateCreate: DateTime.now(),
      },
      {
        id: 39,
        budgetId: 36,
        number: "83990",
        description: "Otros servicios profesionales, técnicos y empresariales n.c.p.",
        dateCreate: DateTime.now(),
      },
      {
        id: 40,
        budgetId: 36,
        number: "84342",
        description: "Servicios de descarga de software de aplicaciones",
        dateCreate: DateTime.now(),
      },
      {
        id: 41,
        budgetId: 36,
        number: "84399",
        description: "Otros servicios de contenidos en línea (on-line) n.c.p.",
        dateCreate: DateTime.now(),
      },
      {
        id: 42,
        budgetId: 36,
        number: "85250",
        description: "Servicios de protección (guardas de seguridad)",
        dateCreate: DateTime.now(),
      },
      {
        id: 43,
        budgetId: 36,
        number: "85330",
        description: "Servicios de limpieza general",
        dateCreate: DateTime.now(),
      },
      {
        id: 44,
        budgetId: 36,
        number: "85961",
        description: "Servicios de organización y asistencia de convenciones",
        dateCreate: DateTime.now(),
      },
      {
        id: 45,
        budgetId: 36,
        number: "85962",
        description: "Servicios de organización y asistencia de ferias comerciales",
        dateCreate: DateTime.now(),
      },
      {
        id: 46,
        budgetId: 36,
        number: "8715299",
        description: "Otros servicios de mantenimiento y reparación de maquinaria y aparatos eléctricos n.c.p.",
        dateCreate: DateTime.now(),
      },
      {
        id: 47,
        budgetId: 36,
        number: "8715699",
        description: "Servicio de mantenimiento y reparación de máquinas de uso general n.c.p.",
        dateCreate: DateTime.now(),
      },
      {
        id: 48,
        budgetId: 36,
        number: "8736099",
        description: "Otros servicios de instalación de maquinaria y aparatos eléctricos n.c.p.",
        dateCreate: DateTime.now(),
      },
      {
        id: 49,
        budgetId: 37,
        number: "91121",
        description: "Servicios de la administración pública relacionados con la educación",
        dateCreate: DateTime.now(),
      },
      {
        id: 50,
        budgetId: 37,
        number: "91122",
        description: "Servicios de la administración pública relacionados con la salud",
        dateCreate: DateTime.now(),
      },
      {
        id: 51,
        budgetId: 37,
        number: "3899998",
        description: "Servicios de educación postsecundaria no superior",
        dateCreate: DateTime.now(),
      },
      {
        id: 52,
        budgetId: 37,
        number: "3899998",
        description: "Servicios de alcantarillado y tratamiento de aguas residuales",
        dateCreate: DateTime.now(),
      }
    ]);
  }
}
